server:
  port: 9003
spring:
  application:
    name: tensquare_qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tensquare.qa.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl