server:
  port: 9002
spring:
  application:
    name: tensquare_recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tensquare.recruit.pojo
  mapper-locations: classpath:mapper/*Mapper.xml