server:
  port: 9004
spring:
  application:
    name: tensquare_article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tensquare.article.pojo
  mapper-locations: classpath:mapper/*Mapper.xml